swagger: "2.0"
info:
  description: "Api que recebe uma lista de urls e um termo a ser buscado, retorna um json com as urls em que o termo foi encontrado, seguidas pela quantidade de ocorrencias."
  version: "1.0"
  title: "FindWordApi"
  contact:
    email: "guicastro.200@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "127.0.0.1:5000"
basePath: "/"

schemes:
- "http"
paths:
  /findword:
    get:
      description: Retorna a quantidade de ocorrências do termo por URL
      operationId: findword
      produces:
        - application/json
      parameters:
        - name: urls
          in: query
          description: Urls que serão usadas na busca
          required: true
          type: string
          format: path
        - name: termo
          in: query
          description: Termo que vai ser buscado nas urls
          required: true
          type: string
          format: string          
      responses:
        '200':
          description: Crawler executado com sucesso
        default:
          description: '{}'
          schema:
            $ref: '#/'